id: ACDC15C42
title: Aspiration Prayer for the Flourishing of the Jonang Teachings
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:01:12.198557
  last_modified_at: 2022-03-01 04:01:12.198564
